orange: [5, 30, 25, 255, 25, 255]
red: [0, 30, 25, 255, 25, 255]
red2: [150, 179, 25, 255, 25, 255]
green: [30, 90, 25, 255, 25, 255]
black: [0, 180, 0, 255, 0, 100]
white: [0, 0, 0, 10, 200, 255]
blue: [80, 145, 25, 255, 25, 255]
yellow: [10, 45, 25, 255, 25, 255]
misc: [0, 180, 0, 255, 0, 255]