# black: [0, 1, 2, 3]
# blue: [4, 5, 6, 7, 8]
# green: [11, 12, 23, 14, 15]
# red: [17, 18, 19, 20, 21, 22, 23]
# yellow: [25, 26]
black: [0]
blue: [4, 5]
green: [10, 11, 13]
red: [15, 16, 19, 18]
yellow: [22, 23]