labels: [
  # "black_circle",
  "black_cross",
  "black_triangle",
  # "blue_circle",
  # "blue_cross",
  # "blue_square",
  # "blue_triangle",
  # "green_circle",
  # "green_square",
  # "green_cross",
  # "green_triangle",
  # "red_circle",
  # "red_square",
  # "red_cross",
  # "red_triangle",
  "number_1",
  "number_2",
  "number_3",
  "number_1_green",
  "number_2_green",
  "number_3_green",
  "number_1_red",
  "number_2_red",
  "number_3_red",
]

coplanar:
  100: [ # dock banners
    # "blue_circle",
    # "blue_cross",
    # "blue_square",
    # "blue_triangle",
    # "green_circle",
    # "green_square",
    # "green_cross",
    # "green_triangle",
    # "red_circle",
    # "red_square",
    # "red_cross",
    # "red_triangle"
    "number_1",
    "number_2",
    "number_3",
    "number_1_green",
    "number_2_green",
    "number_3_green",
    "number_1_red",
    "number_2_red",
    "number_3_red",
    ]

max_iters: 20
dist_thres: 0.1
min_inliers: 15
clust_dist: 0.5
plane_angle_thres: 30.0